---
dependency:
  name: galaxy

driver:
  name: docker

platforms:
  - name: debian-bookworm-invalid
    image: debian:bookworm-slim
    pre_build_image: false
    command: sleep infinity

provisioner:
  name: ansible
  inventory:
    host_vars:
      debian-bookworm-invalid:
        ansible_python_interpreter: /usr/bin/python3
  playbooks:
    prepare: prepare.yml
    converge: converge.yml
    verify: verify.yml

scenario:
  name: invalid_config
  test_sequence:
    - destroy
    - create
    - prepare
    - converge
    - verify
    - destroy
